### PR TITLE
added/updated documentation and related files

### PR DESCRIPTION
**Pull request by KrisThielemans**

### CODE REVIEW

**Comment by KrisThielemans** [comment]
This now fails with https://github.com/ETSInitiative/PRDdefinition/actions/runs/6665422649/job/18114961249?pr=10#step:7:60
```
/usr/share/miniconda/envs/yardl/x86_64-conda-linux-gnu/include/c++/12.3.0/bits/chrono.h:563:17: error: 'S' may be used uninitialized [-Werror=maybe-uninitialized]
  563 |           : __r(static_cast<rep>(__rep)) { }
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
/usr/share/miniconda/envs/yardl/include/date/date.h: In static member function 'static void nlohmann::json_abi_v3_11_2::adl_serializer<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > > >::from_json(const nlohmann::json_abi_v3_11_2::ordered_json&, yardl::DateTime&)':
/usr/share/miniconda/envs/yardl/include/date/date.h:72[61](https://github.com/ETSInitiative/PRDdefinition/actions/runs/6665422649/job/18114961249?pr=10#step:7:62):37: note: 'S' declared here
 7261 |                         long double S;
      |                                     ^
```
@johnstairs @hansenms is there a way to keep `Werror` but ignore such problems? In the mean time, I'll disable this.

**Comment by johnstairs** [comment]
It's strange that we haven't seen this before. It looks like the issue was fixed back in 2021 https://github.com/HowardHinnant/date/pull/698 but there hasn't been a release since. We can put in an inline suppression in yardl :/

**Comment by KrisThielemans** [comment]
I changed to depend on `compilers`, so it's using gcc 12.3.0, while previous runs where with 11.2.0. That's probably why.

I generally find `-Werror` very reliant on the compiler and external libraries doing the correct thing, but I don't know of a way to say "error on warnings on my code only"!

**Comment by johnstairs** [comment]
I tried GCC 13.2.0 on the yardl and a bunch of warnings from dependencies (xtensor/xtl, date.h) pop up (not this one, interestingly). I'll investigate.

**Pull request merged**
